name: Rust Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: ROOT="$(pwd)"; while read in; do cd $in && cargo test --verbose -j 2 --features strict -- --test-threads 2 --nocapture && cd $ROOT; done < .cargo-test-dirs
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run linter
      run: ROOT="$(pwd)"; while read in; do cd $in && cargo clippy --all-targets --all-features -- -D warnings && cd $ROOT; done < .cargo-test-dirs

